version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "${PORT}:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - lotf-network

networks:
  lotf-network:
    external: true
